# Brewfile for new machine
# install homebrew from brew.sh then run `brew bundle`

# apps
tap "homebrew/cask"
cask "docker"
cask "firefox"
cask "google-chrome"
cask "spotify"
cask "viscosity"
cask "visual-studio-code"
cask "zoomus"
cask "cloudapp"

# fonts
tap "homebrew/cask-fonts"
cask "font-fira-code"

# dev - puma dev server
tap "puma/puma"
brew "puma/puma/puma-dev"

# dev - tools
brew "git"
brew "powerline-go"
brew "chruby"
brew "ruby-install"
