config_version = 14

[bar.default]
background_opacity = 0.87999998033046722
center = [ "status", "clock", "screenshot" ]
end = [
    "group:g1",
    "media",
    "caffeine",
    "tray",
    "notifications",
    "clipboard",
    "network",
    "bluetooth",
    "volume",
    "brightness",
    "battery",
    "control-center",
    "session"
]
margin_ends = 4
start = [ "launcher", "group:g2", "workspaces" ]

    [[bar.default.capsule_group]]
    accordion = true
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g1"
    members = [ "cpu", "ram", "network_rx", "network_tx" ]
    opacity = 1.0
    padding = 6.0

    [[bar.default.capsule_group]]
    accordion = false
    accordion_direction = "end"
    enabled = true
    fill = "surface_variant"
    id = "g2"
    members = [ "wallhaven", "wallpaper", "mpvpaper" ]
    opacity = 1.0
    padding = 6.0

[control_center]
sidebar = "full"
sidebar_section = "full"

[dock]
enabled = true
icon_size = 32
main_axis_padding = 12
reserve_space = false
smart_auto_hide = true

[location]
address = "Manchester, NH, US"

[lockscreen_widgets]
enabled = false
schema_version = 2
widget_order = [ "lockscreen-login-box@eDP-1" ]

    [lockscreen_widgets.grid]
    cell_size = 16
    major_interval = 4
    visible = true

    [lockscreen_widgets.widget."lockscreen-login-box@eDP-1"]
    box_height = 196.0
    box_width = 810.0
    cx = 854.0
    cy = 885.0
    output = "eDP-1"
    placement_height = 1067.0
    placement_width = 1707.0
    rotation = 0.0
    type = "login_box"

        [lockscreen_widgets.widget."lockscreen-login-box@eDP-1".settings]
        background_color = "surface_variant"
        background_opacity = 0.88
        background_radius = 12.0
        center_password_text = false
        input_opacity = 1.0
        input_radius = 6.0
        layout = "regular"
        show_caps_lock = true
        show_keyboard_layout = true
        show_login_button = true
        show_media = true
        show_session_buttons = true
        show_unlock_hint = true
        show_weather = true

[nightlight]
enabled = true

[plugins]
enabled = [ "noctalia/mpvpaper", "noctalia/wallhaven", "gabedunn/voxtype" ]

[shell]
avatar_path = "/home/defeated/Pictures/defeated.jpg"
time_format = "{:%-I:%M %p}"

    [shell.panel]
    open_near_click_session = true

    [shell.session]
    grid = true
    grid_columns = 1
    show_shortcuts = false

        [[shell.session.actions]]
        action = "lock_and_suspend"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "3"
        variant = "default"

        [[shell.session.actions]]
        action = "reboot"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "4"
        variant = "default"

        [[shell.session.actions]]
        action = "shutdown"
        countdown_seconds = 0.0
        enabled = true
        shortcut = "5"
        variant = "destructive"

        [[shell.session.actions]]
        action = "lock"
        countdown_seconds = 0.0
        enabled = false
        shortcut = "1"
        variant = "default"

        [[shell.session.actions]]
        action = "logout"
        countdown_seconds = 0.0
        enabled = false
        shortcut = "2"
        variant = "default"

[theme]
builtin = "Tokyo-Night"
community_palette = "Tokyo Night Moon"
mode = "dark"
source = "wallpaper"
wallpaper_scheme = "m3-rainbow"

    [theme.templates]
    builtin_ids = [ "btop", "gtk3", "gtk4", "ghostty", "niri", "starship" ]

[wallpaper.default]
path = "/home/defeated/Pictures/wallhaven-wyw7d7.png"

[wallpaper.last]
path = "/home/defeated/Pictures/wallhaven-wyw7d7.png"

[wallpaper.monitors.eDP-1]
path = "/home/defeated/Pictures/wallhaven-wyw7d7.png"

[weather]
unit = "imperial"

[widget.battery]
display_mode = "graphic"

[widget.brightness]
enabled = false
show_label = false

[widget.clock]
format = "{:%b %d, %Y @ %-I:%M %p}"

[widget.control-center]
enabled = false

[widget.launcher]
glyph = "grid-dots"

[widget.media]
hide_when_no_media = true

[widget.mpvpaper]
type = "noctalia/mpvpaper:mpvpaper"

[widget.network]
show_label = false
show_vpn_label = true
vpn_status = "both"

[widget.notifications]
hide_when_no_unread = true

[widget.screenshot]
capsule = true

[widget.status]
capsule = true
type = "gabedunn/voxtype:status"

[widget.volume]
show_label = false

[widget.wallhaven]
type = "noctalia/wallhaven:wallhaven"

[widget.workspaces]
label_source = "name"